# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 主题 REDEFINE 配置文件 V2
# 作者：EVANNOTFOUND
# GitHub：https://github.com/EvanNotFound/hexo-theme-redefine
# 文档：https://redefine-docs.ohevan.com
# 演示：https://redefine.ohevan.com
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 基本信息 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/info
info:
  # 网站标题
  title: aipno's /
  # 网站副标题
  subtitle:
  # 作者姓名
  author: aipno
  # 网站URL
  url: https://me.iswxl.cn
# 基本信息 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 图片配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/defaults
defaults:
  # 网站图标
  favicon: /images/favicon.ico
  # 网站Logo
  logo: /images/logo.png
  # 网站头像
  avatar: /images/touxiang.jpg
# 图片配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 颜色配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/colors
colors:
  # 主色调
  primary: "#A31F34"
  # 次要颜色（待定）
  secondary:
  # 默认主题模式初始值（将被prefer-color-scheme覆盖）
  default_mode: light # light, dark
# 颜色配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 网站自定义 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/global
global:
  # 自定义全局字体
  fonts:
    # 中文字体
    chinese: 
      enable: false # 是否启用自定义中文字体
      family:  # 字体系列
      url:  # 字体CSS文件URL
    # 英文字体
    english: 
      enable: false # 是否启用自定义英文字体
      family:  # 字体系列
      url:  # 字体CSS文件URL
    # 自定义标题字体（导航栏、侧边栏）
    title:
      enable: false # 是否启用自定义标题字体
      family:  # 字体系列
      url:  # 字体CSS文件URL
  # 内容最大宽度
  content_max_width: 1000px
  # 侧边栏宽度
  sidebar_width: 210px
  # 鼠标悬停效果
  hover:
    shadow: true # 阴影效果
    scale: false # 缩放效果
  # 滚动进度
  scroll_progress:
    bar: false # 进度条
    percentage: true # 百分比
  # 网站计数器
  website_counter:
    url: https://cn.vercount.one/js # 计数器API URL（无需更改）
    enable: true # 是否启用网站计数器
    site_pv: true # 网站页面浏览量
    site_uv: true # 网站独立访客数
    post_pv: true # 文章页面浏览量
  # 是否启用单页体验（使用swup）。参见 https://swup.js.org/。类似于pjax
  single_page: true
  # 是否启用预加载器
  preloader:
    enable: true
    custom_message: # 自定义消息。如果为空，则显示网站标题
  # 侧边工具设置
  side_tools:
    # 是否为设置按钮启用齿轮旋转动画
    gear_rotation: true
    # 是否在页面加载时自动展开工具列表
    auto_expand: false
  # 是否启用开放图谱
  open_graph:
    enable: true
    image: /images/redefine-og.webp  # 默认og:image
    description: Hexo Theme Redefine, Redefine Your Hexo Journey.
  # Google Analytics
  google_analytics:
    enable: false # 是否启用Google Analytics
    id:  # Google Analytics测量ID
# 网站自定义 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束
    

# FONTAWESOME >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/basic/fontawesome
fontawesome: # Pro v6.2.1
  # 细线版本
  thin: false
  # 轻量版本
  light: false
  # 双色版本
  duotone: false
  # 锐利实心版本
  sharp_solid: false
# FONTAWESOME <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 首页横幅 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/home/home_banner
home_banner:
  # 是否启用首页横幅
  enable: true
  # 首页横幅样式
  style: fixed # static 或 fixed
  # 首页横幅图片
  image: 
    light: https://bing.api.iswxl.cn/4k.php
    dark: https://bing.api.iswxl.cn/4k.php
  # 首页横幅标题
  title: aipno's /
  # 首页横幅副标题
  subtitle:
    text: ["hello world"] # 副标题文本，数组
    hitokoto:  # 一言配置
      enable: true # 是否启用一言
      show_author: true # 是否显示作者
      api: https://v1.hitokoto.cn # API URL，可以添加类型，参见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    typing_speed: 100 # 打字速度（毫秒）
    backing_speed: 80 # 回退速度（毫秒）
    starting_delay: 500 # 开始延迟（毫秒）
    backing_delay: 1500 # 回退延迟（毫秒）
    loop: true # 是否循环
    smart_backspace: true # 是否智能回退
  # 首页横幅文本颜色
  text_color: 
    light: "#fff" # 浅色模式
    dark: "#d1d1b6" # 深色模式
  # 文本的特定样式
  text_style: 
    # 标题字体大小
    title_size: 2.8rem
    # 副标题字体大小
    subtitle_size: 1.5rem
    # 标题和副标题之间的行高
    line_height: 1.2
  # 首页横幅自定义字体
  custom_font: 
    # 是否启用自定义字体
    enable: false
    # 字体系列
    family: 
    # 字体CSS文件URL
    url:
  # 首页横幅社交链接
  social_links:
    # 是否启用
    enable: true
    # 社交链接样式
    style: default # default, reverse, center
    # 社交链接
    links:
      - icon: github
        url: https://github.com/aipno
      - icon: email
        url: aipno@iswxl.cn
    # 带二维码抽屉的社交链接
    qrs:
      - icon: weixin
        qr:
      - icon: /images/custom-icon.svg
        qr:
  # 背景信息配置
  bg_info:
    enable: true
    icon: "fa-solid fa-image"
    # 模式：static (静态配置) 或 api (从API获取)
    mode: "api" 
    # 静态模式配置
    static:
      title: "Background Info"
      desc: "This is a background image"
    # API模式配置
    api:
      url: "https://bing.api.iswxl.cn/copyright.php" # API地址
      response_fields:
        title: "title" # 响应JSON中对应的标题字段名
        desc: "copyright"  # 响应JSON中对应的描述字段名
# 首页横幅 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 导航栏 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/home/navbar
navbar:
  # 自动隐藏导航栏
  auto_hide: false
  # 导航栏背景颜色
  color:
    left: "#f78736" #左侧
    right: "#367df7"  #右侧
    transparency: 35 #百分比 (10-99)
  # 导航栏宽度（通常无需修改）
  width:
    home: 1200px #首页
    pages: 1000px #其他页面
  # 导航栏链接
  links:
    Home:
      path: /
      icon: fa-regular fa-house
    Archives:
      path: /archives
      icon: fa-regular fa-archive
    About:
      icon: fa-regular fa-user
      path: /about
    Categories:
      icon: fa-regular fa-folder
      path: /categories
    Tags:
      icon: fa-regular fa-tags
      path: /tags
    Friends:
      icon: fa-regular fa-link
      path: /links

  # 导航栏搜索（本地搜索）。需要hexo-generator-searchdb（npm i hexo-generator-searchdb）。参见 https://github.com/theme-next/hexo-generator-searchdb
  search:
    # 是否启用
    enable: false
    # 页面加载时预加载搜索数据
    preload: true
# 导航栏 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 首页文章设置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/home/home
home:
  # 侧边栏设置
  sidebar:
    enable: true # 是否启用侧边栏
    position: left # 侧边栏位置。left, right
    first_item: menu # 侧边栏第一项。menu, info
    announcement: # 公告文本
    show_on_mobile: true # 是否在移动设备菜单中显示侧边栏导航
    links:
      # Archives: 
      #   path: /archives 
      #   icon: fa-regular fa-archive # 可以为空
      # Tags: 
      #   path: /tags 
      #   icon: fa-regular fa-tags # 可以为空
      # Categories: 
      #   path: /categories 
      #   icon: fa-regular fa-folder # 可以为空
      # ...... # 你可以添加更多
  # 文章日期格式
  article_date_format: auto # auto, relative, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss 等
  # 文章摘要长度
  excerpt_length: 200 # 文章摘要最大长度
  # 文章分类可见性
  categories:
    enable: true  # 是否启用
    limit: 3 # 显示的最大分类数
  # 文章标签可见性
  tags:
    enable: true  # 是否启用
    limit: 3  # 显示的最大标签数
# 首页文章设置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 文章 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/posts/articles
articles:
  # 设置文章样式
  style:
    font_size: 16px # 字体大小
    line_height: 1.5 # 行高
    image_border_radius: 14px # 图片边框圆角
    image_alignment: center # 图片对齐方式。left, center
    image_caption: false # 是否显示图片说明
    link_icon: true # 是否显示链接图标
    delete_mask: false # 为<del>标签添加遮罩效果，默认隐藏内容，悬停时显示
    title_alignment: left # 标题对齐方式。left, center
    headings_top_spacing: # h1-h6标题的顶部间距
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  # 字数统计。需要hexo-wordcount（npm install hexo-wordcount）。参见 https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # 是否启用
    count: true # 是否显示字数统计
    min2read: true # 是否显示阅读时间
  # 作者标签
  author_label: 
    enable: true # 是否启用
    auto: false # 是否自动添加作者标签，例如Lv1, Lv2, Lv3...
    list: []
  # 代码块设置
  code_block:
    copy: true # 是否启用代码块复制按钮
    style: mac # mac | simple
    highlight_theme: # highlightjs代码高亮的颜色方案。预览参见 https://highlightjs.org/examples
      light: github # 浅色模式主题，支持：github, atom-one-light, default
      dark: vs2015 # 深色模式主题，支持：github-dark, monokai-sublime, vs2015, night-owl, atom-one-dark, nord, tokyo-night-dark, a11y-dark, agate
    font: # 自定义字体
      enable: false # 是否启用
      family: # 字体系列
      url: # 字体CSS文件URL
  # 目录设置
  toc:
    enable: true # 是否启用目录
    max_depth: 3 # 目录深度
    number: false # 是否自动为目录添加编号
    expand: true # 是否展开目录
    init_open: true # 默认打开目录
  # 是否启用版权声明
  copyright:
    enable: true # 是否启用
    default: cc_by_nc_sa # 默认许可证，可选：cc_by_nc_sa, cc_by_nd, cc_by_nc, cc_by_sa, cc_by, all_rights_reserved, public_domain
  # 是否为图片启用懒加载
  lazyload: true
  # Pangu.js（自动在中英文之间添加空格）。参见 https://github.com/vinta/pangu.js
  pangu_js: false
  # 文章推荐。需要nodejieba（npm install nodejieba）。从hexo-theme-volantis移植。
  recommendation:
    # 是否启用文章推荐
    enable: false
    # 文章推荐标题
    title: 推荐阅读
    # 显示的最大文章数
    limit: 3
    # 移动端显示的最大文章数
    mobile_limit: 2
    # 占位图片
    placeholder: /images/wallhaven-wqery6-light.webp
    # 跳过目录
    skip_dirs: []
# 文章 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 评论 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/posts/comment
comment:
  # 是否启用评论
  enable: false
  # 评论系统
  system: waline # waline, gitalk, twikoo, giscus, utterances, artalk
  # 系统配置
  config:
    # Waline评论系统。参见 https://waline.js.org/
    waline:
      serverUrl: https://example.example.com # Waline服务器URL。例如 https://example.example.com
      lang: zh-CN # Waline语言。例如 zh-CN, en-US。参见 https://waline.js.org/guide/client/i18n.html
      emoji: [] # Waline表情，参见 https://waline.js.org/guide/features/emoji.html
      recaptchaV3Key: # Google reCAPTCHA v3密钥。参见 https://waline.js.org/reference/client/props.html#recaptchav3key
      turnstileKey: # Turnstile密钥。参见 https://waline.js.org/reference/client/props.html#turnstilekey
      reaction: false # Waline反应。参见 https://waline.js.org/reference/client/props.html#reaction
    # Gitalk评论系统。参见 https://github.com/gitalk/gitalk
    gitalk:
      clientID: # GitHub应用程序客户端ID
      clientSecret: # GitHub应用程序客户端密钥
      repo: # GitHub仓库
      owner: # GitHub仓库所有者
      proxy: # GitHub仓库代理
    # Twikoo评论系统。参见 https://twikoo.js.org/
    twikoo:
      version: 1.6.10 # Twikoo版本，如果你不知道这是什么就不要修改
      server_url: # Twikoo服务器URL。例如 https://example.example.com
      region: # Twikoo区域。可以为空
    # Giscus评论系统。参见 https://giscus.app/
    giscus:
      repo: # Github仓库名称 例如 EvanNotFound/hexo-theme-redefine
      repo_id: # Github仓库ID
      category: # Github讨论类别
      category_id: # Github讨论类别ID
      mapping: pathname # 使用哪个值作为页面的唯一标识符。例如 pathname, url, title, og:title。启用PJAX时不要使用og:title，因为pjax在页面变化时不会更新og:title
      strict: 0 # 是否启用严格模式。例如 0, 1
      reactions_enabled: 1 # 是否启用反应。例如 0, 1
      emit_metadata: 0 # 是否发送元数据。例如 0, 1
      lang: en # Giscus语言。例如 en, zh-CN, zh-TW
      input_position: bottom # 将评论框放置在评论上方/下方。例如 top, bottom
      loading: lazy # 延迟加载评论
    # Artalk评论系统。参见 https://artalk.js.org/
    artalk:
      server: # Artalk服务器URL。例如 https://artalk.example.com
      site: # Artalk后台显示的站点名称（应与服务器端站点配置匹配）
    # Utterances评论系统。参见 https://utteranc.es/
    utterances:
      repo: # GitHub仓库名称 例如 owner/repo（必须启用Issues）
      issue_term: pathname # pathname, url, title, og:title（建议：单页模式使用pathname）
      issue_number: # 使用特定的issue编号代替issue_term
      label: # 创建的issue的可选标签
      theme_light: github-light # 浅色主题
      theme_dark: github-dark # 深色主题
# 评论 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 页脚 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/footer
footer:
  # 显示网站运行时间
  runtime: true # 是否显示网站运行时间
  # 页脚中的图标，此处填写fontawesome图标代码
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  # 网站开始时间，格式：YYYY/MM/DD HH:mm:ss
  start: 2025/9/7 14:00:00
  # 站点统计
  statistics: true # 是否显示站点统计（总文章数，总字数）
  # 页脚消息
  customize:
  # ICP备案号。参见 https://beian.miit.gov.cn/
  icp:
    enable: true # 是否启用
    number: 鲁ICP备2025142845号-1
    url: https://beian.miit.gov.cn/
  gongan:
    enable: true
    number: 鲁公网安备37172402000442号
    url: https://beian.mps.gov.cn/#/query/webSearch?code=37172402000442
  mengicp:
    enable: true
    number: 萌ICP备20250716号
    url: https://icp.gov.moe/?keyword=20250716
# 页脚 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 注入 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/inject
inject:
  # 是否启用注入
  enable: true
  # 注入自定义head html代码
  head: 
    - <script defer src="https://analyze.iswxl.cn/script.js" data-website-id="669d8db9-b0b5-48b3-a171-7cad9060f158"></script>
    -
  # 注入自定义footer html代码
  footer:
    -
    -
# 注入 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 插件 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/plugins
plugins:
  # RSS订阅。需要hexo-generator-feed（npm i hexo-generator-feed）。参见 https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: false # 是否启用
  # Aplayer。参见 https://github.com/DIYgod/APlayer
  aplayer:
    enable: true # 是否启用
    type: fixed # fixed, mini
    audios:
      - name: 如果
        artist: 菠萝赛东/Bo Peep
        url: /music/如果-菠萝赛东&Bo Peep/菠萝赛东,Bo Peep - 如果.mp3
        cover: /music/如果-菠萝赛东&Bo Peep/cover.png
        lrc: /music/如果-菠萝赛东&Bo Peep/菠萝赛东,Bo Peep - 如果.lrc
  # Mermaid JS。需要hexo-filter-mermaid-diagrams（npm i hexo-filter-mermaid-diagrams）。参见 https://mermaid.js.org/
  mermaid:
    enable: false # 是否启用mermaid
    version: "11.4.1" # 默认 v11.4.1
    theme:
      light: "default"
      dark: "dark"
# 插件 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 页面模板 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/page_templates
page_templates:
  # 友链页面列数
  friends_column: 2
  # 标签页面样式
  tags_style: blur # blur, cloud
  # 瀑布流页面批次大小
  masonry:
    batch_size: 12
    initial_batch_size: 24
# 页面模板 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/cdn
cdn:
  # 是否启用CDN
  enable: false
  # CDN提供商
  provider: npmmirror # npmmirror, zstatic, cdnjs, jsdelivr, unpkg, custom
  # 自定义CDN URL
  # 格式示例：https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
  # ${path}必须指向主题"source"文件夹的根目录
  custom_url: 
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 开发者模式 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档：https://redefine-docs.ohevan.com/developer
developer:
  # 是否启用开发者模式（仅适用于想要修改主题源代码的开发者，不适用于普通用户）
  enable: false
# 开发者模式 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束
